# ========================
# データベース設定（PostgreSQL）
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_gacha_db
spring.datasource.username=postgres
spring.datasource.password=918188661w

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# HotPepper API設定
# ========================
hotpepper.api.key=b5fa132544a57e75
hotpepper.api.url=https://webservice.recruit.co.jp/hotpepper/gourmet/v1/

# ========================
# サーバー設定
# ========================
server.port=8080

# ========================
# ログ設定
# ========================
logging.level.com.example.backend=DEBUG

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

logging.level.org.springframework.security=DEBUG